name: patient

services:
  web:
    container_name: patient-web
    build:
      context: .
      args:
        uid: ${UID:-1000}
    ports:
      - 81:80
      - 5174:5173
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    labels:
      - "traefik.docker.network=tinrx"
      - "traefik.http.routers.patient-web.rule=Host(`patient.localhost`)"
    volumes:
      - ./:/var/www/html
    networks:
      - tinrx
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0
    container_name: patient-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - patient_mysql_data:/var/lib/mysql
      - ./database/sql:/sql
    networks:
      - tinrx
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - tinrx

networks:
  tinrx:
    driver: bridge

volumes:
  patient_mysql_data:
    driver: local
